[build]
builder = "nixpacks"

[deploy]
startCommand = "cd kasir_forumkm && /opt/venv/bin/python manage.py migrate && /opt/venv/bin/python manage.py collectstatic --noinput && gunicorn kasir_forumkm.wsgi:application --bind 0.0.0.0:$PORT"