# Generated by Django 6.0.5 on 2026-05-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('status_halal', models.CharField(choices=[('halal', 'Halal'), ('tidak_halal', 'Tidak Halal'), ('perlu_cek', 'Perlu Dicek')], default='perlu_cek', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.kategori')),
            ],
        ),
    ]
