# Generated by Django 6.0.5 on 2026-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='kembalian',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_bayar',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('qris', 'QRIS')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='uang_bayar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
